# Generated by Django 4.2.7 on 2023-11-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rating'),
        ('movie', '0002_alter_movie_rating_alter_movie_runtime'),
    ]

    operations = [
    ]
